"""The default builder: real files, no AI, free. See docs/V2-PLAN.md Step 8.

Writes just enough that `git init / add / commit` has something genuine to commit —
a README describing the note and a placeholder script. Step 12 swaps in a real Claude
Code builder behind the same interface; this one never costs anything.
"""

from __future__ import annotations

from pathlib import Path

from axon.models import ClassifiedNote


class MockBuilder:
    name = "mock"

    def build(self, note: ClassifiedNote, project_dir: Path) -> list[str]:
        readme = project_dir / "README.md"
        readme.write_text(
            f"# {note.text}\n\n"
            "Generated by Axon's mock builder (free, offline, no AI).\n"
            f"Note #{note.note_id}: {note.text}\n",
            encoding="utf-8",
        )

        main = project_dir / "main.py"
        main.write_text(
            f'"""Placeholder project for: {note.text}"""\n\n'
            "def main() -> None:\n"
            "    print(\"hello from an Axon-built project\")\n\n\n"
            'if __name__ == "__main__":\n'
            "    main()\n",
            encoding="utf-8",
        )

        return ["README.md", "main.py"]
